config/routes.rb
Tmca::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  match '/search', :to => 'search#index', :as => 'search', :via => :get
  match '/information', :to => 'informations#index', :as => 'information', :via => :get
  
  namespace :admin do
    
    match '/', :to => 'sessions#new', :as => 'login', :via => :get    
    match '/logout', :to => 'sessions#destroy', :as => 'logout', :via => :get
    match 'install', :to => 'installs#new', :via => :get
    resources :sessions
    
    resources :currents do 
      collection do
        delete 'cancel_main'
      end
    end
    
    resources :exhibitions do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
      
      
    end
    
    resources :news
    resources :educations do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :installs
    resources :events do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :informations
    resources :mailinglists do 
      collection do 
        get 'export_excel'
      end
    end

    resources :mailingtemplates
    
    resources :pictures do
      collection do
        delete 'delete_files'
      end
    end
    
    resources :pdfs do
      collection do
        delete 'delete_files'
      end
    end
    
  end
  
  resources :events
  resources :exhibitions
  resources :news
  resources :educations
  resources :mailinglists

  
  root :to => "welcomes#index"
end

app/models/mailinglist.rb
# -*- encoding : utf-8 -*-
class Mailinglist < ActiveRecord::Base
  acts_as_xlsx

  set_primary_key :id
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/admin/mailinglists_controller.rb
# -*- encoding : utf-8 -*-
class Admin::MailinglistsController < ApplicationController
  before_filter :login_required
  layout 'admin'
  def index
  
  if params[:page]
      @page = params[:page]
    else
      @page = 1
    end
    
    @mailinglists = Mailinglist.order('created_at DESC').paginate(:page => @page, :per_page => 10)
    
  end

  def export_excel
    @mailinglists = Mailinglist.all
    
    send_data Mailinglist.to_xlsx.to_stream.read, :filename => 'mailinglists.xlsx', :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
  end
  
  
  def new
  end
  
  def create
    
    @template = Mailingtemplate.new({
      :title => params[:title],
      :description => params[:description]
    })
    
    @template.save
    
    @attachments = params[:attachments]
    @attachment_filenames = []

    @attachments.each_with_index do |attachment, idx|
      File.open("#{Rails.root.to_s}/tmp/#{attachment.original_filename}", "wb") do |f|
        f.write attachment.read
      end

      @attachment_filenames <<  {
        tempfile_path: "#{Rails.root.to_s}/tmp/#{attachment.original_filename}",
        original_filename: attachment.original_filename,
        content_type: attachment.content_type
      }
    end


    Mailinglist.all.each do |user|
      MalinglistMailer.delay.mailinglist_mail(user.email, @template, @attachment_filenames) if user.present? and user.email.present? and @template.present?
    end
     
    
    respond_to do |format|
      format.html {redirect_to admin_mailinglists_path, :notice => '성공적으로 메일을 보냈습니다.'}
    end
      
  end

  def destroy
    @mailinglist = Mailinglist.find(params[:id])
    @mailinglist.destroy
    redirect_to admin_mailinglists_path, :notice => '성공적으로 삭제했습니다.'

  end
end

app/controllers/mailinglists_controller.rb
# -*- encoding : utf-8 -*-
class MailinglistsController < ApplicationController
  def new
    @mailinglist = Mailinglist.new
    render :layout => false
  end

  def create
    @mailinglist = Mailinglist.new(params[:mailinglist])
    
    respond_to do |format|
      if @mailinglist.save
        format.json {render :json => {:success => true, :message => '성공적으로 메일링 리스트에 등록되었습니다.'}}
      else 
        format.json {render :json => {:success => false}}
      end
    end
  end
  
  def destroy
    @mailinglist = Mailinglist.find_by_token(params[:token])
    respond_to do |format|
      if @mailinglist != nil
        @mailnglist.destroy
        format.html {redirect_to root_path, :notice => '성공적으로 메일링 리스트에서 제거되었습니다.'}
      else
        format.html {redirect_to root_path, :alert => '메일링 리스트에서 제거할 수 없습니다.'}
      end
    end
    
  end
end

app/helpers/admin/mailinglists_helper.rb
# -*- encoding : utf-8 -*-
module Admin::MailinglistsHelper
end

app/helpers/mailinglists_helper.rb
# -*- encoding : utf-8 -*-
module MailinglistsHelper
end

app/views/admin/mailinglists/_tabs.html.erb
<ul class="nav nav-tabs">
  <% if params[:action] == 'index' && params[:controller] == 'admin/mailinglists' %>
    <li class="active">
  <% else %>
    <li>
  <% end %>   
  <%= link_to '메일링 리스트 가입자', admin_mailinglists_path %></li>
  
  
  <% if params[:controller] == 'admin/mailingtemplates' && params[:action] == 'index' %>
    <li class="active">
  <% else %>
    <li>
  <% end %>   
  <%= link_to '메일링 리스트 전송내역', admin_mailingtemplates_path %></li>
  
  <% if params[:action] == 'new' %>
    <li class="active">
  <% else %>
    <li>
  <% end %>  
  <%= link_to '메일링리스트 보내기', new_admin_mailinglist_path %></li>
</ul>

app/views/admin/mailinglists/index.html.erb
<%= render 'admin/mailinglists/tabs' %>
 
<h2 class="title">
  메일링리스트 가입자
</h2>


<%= link_to 'Save(.xls)', export_excel_admin_mailinglists_path, :class => 'btn-primary btn' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="first">#</th>
      <th>E-Mail</th>
      <th>가입일</th>
      <th class="last">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @mailinglists.each_with_index do |mailinglist, index| %>
    <tr>
      <td><%= mailinglist.id %></td>
      <td><%= mailinglist.email %></td>
      <td><%= mailinglist.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= link_to '탈퇴', admin_mailinglist_path(mailinglist), :method => :delete, :confirm => '정말 탈퇴시키시겠습니까?' %></td>
    </tr>
  <% end %>
</tbody></table>
<%= will_paginate @mailinglists %>

app/views/admin/mailinglists/new.html.erb
<%= render 'admin/mailinglists/tabs' %>
  
<div id="list" class="block">
  <div class="content">
    <h2 class="title">
      메일링리스트 보내기
    </h2>
    <div class="inner">
      <%= form_tag admin_mailinglists_path, :multipart => true, :class => 'form' do %>
        <div class="group">
          <%= label_tag :title, '제목' %>
          <%= text_field_tag :title,  '', :class => 'input-xlarge' %>
        </div>        
        <div class="group">
          <%= label_tag :description, '내용' %>
          <%= text_area_tag :description, '', :class => 'text_area', :id => 'newsNewTextArea' %>
        </div>
        
        <div class="group" style="margin-top:20px">
          <%= label_tag 'attachments[]', '첨부 파일', :id => 'label_attachment_01' %>
          <%= file_field_tag 'attachments[]', :id => 'file_attachment_01' %>
          <p>
            그림 파일인 경우 자동으로 본문의 맨 앞에 삽입됩니다.
          </p>
        </div>
        
        
        <div class="group">
          <%= label_tag 'attachments[]', '첨부 파일', :id => 'label_attachment_02' %>
          <%= file_field_tag 'attachments[]', :id => 'file_attachment_02' %>
          <p>
            그림 파일인 경우 자동으로 본문의 맨 앞에 삽입됩니다.
          </p>
        </div>
        
        
        <div class="group">
          <%= label_tag 'attachments[]', '첨부 파일', :id => 'label_attachment_03' %>
          <%= file_field_tag 'attachments[]', :id => 'file_attachment_03' %>
           <p>
            그림 파일인 경우 자동으로 본문의 맨 앞에 삽입됩니다.
          </p>
        </div>
        
        
        <div class="form-actions">
          <%= button_tag '저장', :class => 'btn btn-primary' %>
          <%= link_to '취소', admin_exhibitions_path %>
        </div>
      
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'admin/news/new' %>