config/routes.rb
Tmca::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  match '/search', :to => 'search#index', :as => 'search', :via => :get
  match '/information', :to => 'informations#index', :as => 'information', :via => :get
  
  namespace :admin do
    
    match '/', :to => 'sessions#new', :as => 'login', :via => :get    
    match '/logout', :to => 'sessions#destroy', :as => 'logout', :via => :get
    match 'install', :to => 'installs#new', :via => :get
    resources :sessions
    
    resources :currents do 
      collection do
        delete 'cancel_main'
      end
    end
    
    resources :exhibitions do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
      
      
    end
    
    resources :news
    resources :educations do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :installs
    resources :events do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :informations
    resources :mailinglists do 
      collection do 
        get 'export_excel'
      end
    end

    resources :mailingtemplates
    
    resources :pictures do
      collection do
        delete 'delete_files'
      end
    end
    
    resources :pdfs do
      collection do
        delete 'delete_files'
      end
    end
    
  end
  
  resources :events
  resources :exhibitions
  resources :news
  resources :educations
  resources :mailinglists

  
  root :to => "welcomes#index"
end

app/models/exhibition.rb
# -*- encoding : utf-8 -*-
class Exhibition < ActiveRecord::Base
  belongs_to :category
  has_many :pictures, :as => :pictureable, :dependent => :destroy
  has_many :pdfs, :as => :pdfable, :dependent => :destroy
   # attr_accessor :crop_medium_x, :crop_medium_y, :crop_medium_width, :crop_medium_height, :crop_thumb_x, :crop_thumb_y, :crop_thumb_width, :crop_thumb_height
    # after_update :reprocess_bigphoto, :if => :cropping?  
    # 
    # def cropping?  
    #   !crop_medium_x.blank? && !crop_medium_y.blank? && !crop_medium_width.blank? && !crop_medium_height_blank? && !crop_thumb_x_blank? && !crop_thumb_y.blank? && !crop_thumb_width.blank? && !crop_thumb_height.blank?
    # end  
    # 
    # private  
    # def reprocess_bigphoto
    #   bigphoto.reprocess!  
    # end
  CATEGORY = {1 => 'Exhibition', 2 => 'Education', 3 => 'Event', 4 => 'News'}
    
  def currentPhoto(varient = nil)
    if self.pictures.first != nil
      if varient.present? 
        self.pictures.first.photo.url(varient)
      else
        self.pictures.first.photo.url(:original) 
      end
    else
      "default_exhibition.png"
    end
  end
  
  def is_main?
    Current.where(:exhibition_id => self.id).count > 0
  end
      
  def start_date_rescued
    if self.start_date.present?
      self.start_date
    else
      DateTime.now
    end
  end
  
  def end_date_rescued
    if self.end_date.present?
      self.end_date
    else
      DateTime.now
    end
    
  end
  
end

app/controllers/admin/events_controller.rb
# -*- encoding : utf-8 -*-
class Admin::EventsController < ApplicationController
   before_filter :login_required
   layout 'admin'

   def index
     if params[:page]
       @page = params[:page]
     else
       @page = 1
     end
     
     # ExpWeblogTitle.all.each do |weblog_title|
     #   entry_id = weblog_title.entry_id.to_i
     #   categorypost = ExpCategoryPost.find_by_entry_id(entry_id)
     #   
     #   begin
     #     if categorypost.cat_id == 6
     #   
     #          
     #       if weblog_title.year.to_i < 2000
     #         logger.info weblog_title.title
     #         
     #         @exhibition = Exhibition.new
     #         @exhibition.title = weblog_title.title
     #         descData = ExpWeblogData.find_by_entry_id(entry_id)
     #         @exhibition.description = descData.field_id_1 + descData.field_id_2 + descData.field_id_3
     #         @exhibition.start_date = Date.new(weblog_title.year.to_i, weblog_title.month.to_i, weblog_title.day.to_i)
     #         @exhibition.end_date = Date.new(weblog_title.year.to_i, weblog_title.month.to_i, weblog_title.day.to_i)
     #         @exhibition.category_id = 3
     #         @exhibition.save
     #       end
     #     
     #     end
     #    rescue
     #    end
     #    
     # end
     

     @exhibitions = Exhibition.where("category_id = ?", 3).paginate(:page => @page, :per_page => 10).order('start_date DESC')
   end

   def set_current
      @exhibition = Exhibition.find(params[:id])
      @ex_exhibitions = Exhibition.where("category_id = ? AND current = ?", 3, true)
      @ex_exhibitions.each do |ex_exhibition|
        ex_exhibition.current = false
        ex_exhibition.save
      end

      if !@exhibition.upcoming
        @exhibition.current = !@exhibition.current
        respond_to do |format|
          if @exhibition.save
            format.html {redirect_to admin_events_path, :notice => '성공적으로 변경하였습니다.'}
          else
            format.html {redirect_to admin_events_path, :notice => '오류가 발생하였습니다.'}
          end
        end
       else
          @exhibition.upcoming = false
          @exhibition.current = true
          respond_to do |format|
            if @exhibition.save
              format.html {redirect_to admin_exhibitions_path, :notice => '성공적으로 변경하였습니다.'}
            else
              format.html {redirect_to admin_exhibitions_path, :notice => '오류가 발생하였습니다.'}
            end
          end

        end
      
    end

    def new
      @exhibition = Exhibition.new
      @exhibition.title = "title"
      @exhibition.description = "설명을 적어주세요"
      @exhibition.category_id = 3
      @exhibition.save

      redirect_to edit_admin_event_path(@exhibition)
    end


    def set_upcoming
      @exhibition = Exhibition.find(params[:id])
      @ex_exhibitions = Exhibition.where("category_id = ? AND upcoming = ?", 3, true)
      @ex_exhibitions.each do |ex_exhibition|
        ex_exhibition.upcoming = false
        ex_exhibition.save
      end    


      if !@exhibition.current 
        @exhibition.upcoming =!@exhibition.upcoming
        respond_to do |format|
          if @exhibition.save
            format.html {redirect_to admin_events_path, :notice => '성공적으로 변경하였습니다.'}
          else
            format.html {redirect_to admin_events_path, :notice => '오류가 발생하였습니다.'}
          end
        end
      else
        @exhibition.current = false
        @exhibition.upcoming = true

        respond_to do |format|
          if @exhibition.save
            format.html {redirect_to admin_exhibitions_path, :notice => '성공적으로 변경하였습니다.'}
          else
            format.html {redirect_to admin_exhibitions_path, :notice => '오류가 발생하였습니다.'}
          end
        end

      end
      

    end

   def create
     @exhibition = Exhibition.new(params[:exhibition])
     @exhibition.category_id = 3
     respond_to do |format|
       if @exhibition.save
         format.html {redirect_to admin_events_path, :notice => '전시가 성공적으로 생성되었습니다.'}
       else
         format.html {redirect_to admin_events_path, :alert => '전시 생성이 실패하였습니다.'}
       end
     end
   end

   def show
   end

   def edit
     @exhibition = Exhibition.find(params[:id])
   end

   def update
     @exhibition = Exhibition.find(params[:id])   
     respond_to do |format|
       if @exhibition.update_attributes(params[:exhibition])
         format.html {redirect_to admin_events_path, :notice => '전시가 성공적으로 수정되었습니다.' }
       else
         format.html {redirect_to admin_events_path, :alert => '전시 수정 중 오류가 발생하였습니다.'}
       end
     end
   end

   def destroy
     @exhibition = Exhibition.find(params[:id])
     @exhibition.destroy

     respond_to do |format|
       format.html {redirect_to admin_events_path, :notice => '성공적으로 삭제하였습니다.'}
     end
   end

end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  def index
    @current = Exhibition.where("current = ? AND category_id = ?", true, 3).first
    @upcoming = Exhibition.where("upcoming = ? AND category_id = ?", true, 3).first
    @exhibitions = {}
    
    
    @exs = Exhibition.where("current = ? AND upcoming = ? AND category_id = ? AND start_date IS NOT NULL", false, false, 3).order("start_date DESC")
    @years = []
    @exs.each do |ex|
      year = ex.start_date_rescued.strftime("%Y")
      @years << year.to_i
      if @exhibitions[year.to_s] == nil
        @exhibitions[year.to_s] =[]
      end
      @exhibitions[year.to_s] << ex
    end
    
    @years.uniq!
    @years.sort! {|a, b| b <=> a}
    
    
    
  end
  
  
  def show
    @event = Exhibition.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
# -*- encoding : utf-8 -*-
module Admin::EventsHelper
end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/views/admin/events/_tabs.html.erb
<ul class="nav nav-tabs">
  <% if params[:action] == 'index' %>
    <li class="active">
  <% else %>
    <li>
  <% end %>   
  <%= link_to '이벤트 목록', admin_events_path %></li>
  
  <% if params[:action] == 'edit' %>
    <li class="active">
  <% else %>
    <li>
  <% end %>  
  <%= link_to '새 이벤트 생성', new_admin_event_path %></li>
</ul>

app/views/admin/events/edit.html.erb
<script>
  var exhibition_id = <%= @exhibition.id %>;
</script>
<div id="list" class="block">
  <%= render 'admin/events/tabs' %>
  <div class="content">
    <h2 class="title">
      새 이벤트 생성
    </h2>
    <div class="inner">
      <%= form_tag admin_event_path(@exhibition), :multipart => true, :class => 'form', :id => 'exhibitionEditForm' do %>
        
        <%= hidden_field_tag '_method', 'put' %>
          
        <div class="group">
          <%= label_tag 'exhibition[title]', '제목' %>
          <%= text_field_tag 'exhibition[title]', @exhibition.title, :class => 'text_field' %>
        </div>
      
        
        <div class="group">
          <%= label_tag 'exhibition[start_date]', '이벤트 시작일' %>
          <%= date_select 'exhibition', 'start_date', :default => @exhibition.start_date %>
        </div>
        
        <div class="group">
          <%= label_tag 'exhibition[end_date]', '이벤트 종료일' %>
          <%= date_select 'exhibition', 'end_date', :default => @exhibition.end_date %>
        </div>
        
        <div class="group">
          <%= label_tag 'exhibition[description]', '내용' %>
          <%= text_area_tag 'exhibition[description]', @exhibition.description, :class => 'text_area', :id => 'exhibitionNewTextArea' %>
        </div>
               
        <h3 class="upload-title">
          이미지 업로드
        </h3>   
        <div id="uploader_image" class="uploader">
			    <div class="docuUploaderTable">
				    <table class="table table-striped">
    				  <thead>
      					<tr>
      						<th class="select span1"><%= check_box_tag 'descUploaderChkToggle', '1' %></th>
      						<th class="title">파일이름</th>
      						<th class="status span1">
      						  상태
      						</th>
      						<th class="size span2">사이즈</th>
      				  </tr>
      				</thead>
  				
    					<tbody>

    						  <% @exhibition.pictures.each do |picture| %>
    							  <tr>
    							    <td class="select"><%= check_box_tag 'picture_ids[]', 'picture-' + picture.id.to_s, false, :rel => picture.photo.url %>

    							    <td class="title"><%= picture.photo_file_name%></td>
    							    <td class="status">
    					          <%= image_tag 'validate_ok.gif' %>
    							    </td>
    							    <td class="size"><%= (picture.photo_file_size / 1000).floor %> KB</td>
    							  </tr>
    							<% end %>
    					</tbody>
    				</table>
		      </div>
			    <div class="control" id ="docuImgUploadContainer">
    		    <%= link_to 'Browse…', '#', :class => 'btn btn-primary', :id => 'docuImgSelectBtn' %>
    		    <%= link_to 'Delete Selected', '#', :class => 'btn', :id => 'docuImgDeleteBtn' %>
    			</div>
    		</div>

      
      <h3 class="upload-title">
        PDF, HWP 업로드
      </h3>
      <div id="uploader_pdf" class="uploader">
				<div class="docuPdfUploaderTable">
					<table class="table table-striped">
					  <thead>
  						<tr>
  							<th class="select span1"><%= check_box_tag 'pdfUploaderChkToggle', '1' %></th>
  							<th class="title">파일이름</th>
  							<th class="status span1">
  							  상태
  							</th>
  							<th class="size span2">사이즈</th>
  						</tr>
  					</thead>
  					
						<tbody>

  						  <% @exhibition.pdfs.each do |pdf| %>
  							  <tr>
  							    <td class="select"><%= check_box_tag 'pdf_ids[]', 'pdf-' + pdf.id.to_s, false, :rel => pdf.attachment.url %>

  							    <td class="title"><%= pdf.attachment_file_name%></td>
  							    <td class="status">
  					          <%= image_tag 'validate_ok.gif' %>
  							    </td>
  							    <td class="size"><%= (pdf.attachment_file_size / 1000).floor %> KB</td>
  							  </tr>
  							<% end %>
						</tbody>
					</table>
			  </div>
				<div class="control" id ="docuPdfUploadContainer">
			    <%= link_to 'Browse...', '#', :class => 'btn btn-primary', :id => 'docuPdfSelectBtn' %>
			    <%= link_to 'Delete Selected', '#', :class => 'btn', :id => 'docuPdfDeleteBtn' %>
				</div>
      </div>


       <div class="form-actions">
        <%= button_tag '저장', :class => 'btn btn-primary' %>
        <%= link_to '취소', admin_events_path %>
      </div>
        
        
      <% end %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'admin/exhibitions/edit' %>

app/views/admin/events/index.html.erb
<%= render 'admin/events/tabs' %>


<h2 class="title">
  이벤트 목록
</h2>

  <table class="table table-striped">
          <thead>
            <tr>
            <th class="first">#</th>
            <th></th>
            <th>
              시작일
            </th>
            <th>이벤트 제목</th>      
            <th>메인</th>
            <th>현재</th>
            <th>예정</th>
            <th class="last">&nbsp;</th>
          </tr>

          </thead>
          <tbody>          
            <% @exhibitions.each_with_index do |exhibition, index| %>
            <tr>
              <td><%= exhibition.id %></td>
              <td></td>
              <td>
                <%= exhibition.start_date_rescued.strftime("%Y/%m/%d") %>-<br/>
                <%= exhibition.end_date_rescued.strftime("%Y/%m/%d") %><br/>
                
              </td>
              <td><%= link_to exhibition.title, exhibition_path(exhibition) %></td>
              <td>
                 <% if exhibition.is_main? %>
                   현재 메인<br/>
               
               <%= link_to '취소', cancel_main_admin_currents_path(:exhibition_id => exhibition.id), :method => :delete, :confirm => '메인 지정을 취소하시겠습니까?' %>

                 <% else %>
                   
                   <%= link_to '메인 지정', admin_currents_path(:exhibition_id => exhibition.id), :method => :post, :confirm => '메인으로 지정하시겠습니까?' %>
                 <% end %>
              </td>
              <td>
               <% if !exhibition.current %>
                    <%= link_to '현재 지정', set_current_admin_event_path(exhibition), :method => :put, :confirm => '현재 이벤트로 지정하시겠습니까?' %>
                 <% else %> 
                  현재
                  <%= link_to '취소', set_current_admin_event_path(exhibition), :method => :put, :confirm => '현재 이벤트 지정을 취소하시겠습니까?' %>
                 <% end %>
              </td>
              <td>
                <% if !exhibition.upcoming %>
                    <%= link_to '예정 지정', set_upcoming_admin_event_path(exhibition), :method => :put, :confirm => '예정 이벤트로 지정하시겠습니까?' %>
                 <% else %>
                   예정
                    <%= link_to '쥐소', set_upcoming_admin_event_path(exhibition), :method => :put, :confirm => '예정 이벤트 지정을 취소하시겠습니까?' %>
                 <% end %>
              </td>
                
              <td>         
              <%= link_to '수정', edit_admin_event_path(exhibition) %> | <%= link_to '삭제', admin_event_path(exhibition), :method => :delete, :confirm => '정말 이벤트를 삭제하시겠습니까?' %></td>
            </tr>
          <% end %>
        </tbody></table>
        
        <%= will_paginate @exhibitions %>