config/routes.rb
Tmca::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  match '/search', :to => 'search#index', :as => 'search', :via => :get
  match '/information', :to => 'informations#index', :as => 'information', :via => :get
  
  namespace :admin do
    
    match '/', :to => 'sessions#new', :as => 'login', :via => :get    
    match '/logout', :to => 'sessions#destroy', :as => 'logout', :via => :get
    match 'install', :to => 'installs#new', :via => :get
    resources :sessions
    
    resources :currents do 
      collection do
        delete 'cancel_main'
      end
    end
    
    resources :exhibitions do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
      
      
    end
    
    resources :news
    resources :educations do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :installs
    resources :events do
      member do
        put 'set_current'
        put 'set_upcoming'
      end
    end
    resources :informations
    resources :mailinglists do 
      collection do 
        get 'export_excel'
      end
    end

    resources :mailingtemplates
    
    resources :pictures do
      collection do
        delete 'delete_files'
      end
    end
    
    resources :pdfs do
      collection do
        delete 'delete_files'
      end
    end
    
  end
  
  resources :events
  resources :exhibitions
  resources :news
  resources :educations
  resources :mailinglists

  
  root :to => "welcomes#index"
end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base
  has_many :exhibitions
end

app/models/current.rb
# -*- encoding : utf-8 -*-
class Current < ActiveRecord::Base
  belongs_to :exhibition
end

app/models/exhibition.rb
# -*- encoding : utf-8 -*-
class Exhibition < ActiveRecord::Base
  belongs_to :category
  has_many :pictures, :as => :pictureable, :dependent => :destroy
  has_many :pdfs, :as => :pdfable, :dependent => :destroy
   # attr_accessor :crop_medium_x, :crop_medium_y, :crop_medium_width, :crop_medium_height, :crop_thumb_x, :crop_thumb_y, :crop_thumb_width, :crop_thumb_height
    # after_update :reprocess_bigphoto, :if => :cropping?  
    # 
    # def cropping?  
    #   !crop_medium_x.blank? && !crop_medium_y.blank? && !crop_medium_width.blank? && !crop_medium_height_blank? && !crop_thumb_x_blank? && !crop_thumb_y.blank? && !crop_thumb_width.blank? && !crop_thumb_height.blank?
    # end  
    # 
    # private  
    # def reprocess_bigphoto
    #   bigphoto.reprocess!  
    # end
  CATEGORY = {1 => 'Exhibition', 2 => 'Education', 3 => 'Event', 4 => 'News'}
    
  def currentPhoto(varient = nil)
    if self.pictures.first != nil
      if varient.present? 
        self.pictures.first.photo.url(varient)
      else
        self.pictures.first.photo.url(:original) 
      end
    else
      "default_exhibition.png"
    end
  end
  
  def is_main?
    Current.where(:exhibition_id => self.id).count > 0
  end
      
  def start_date_rescued
    if self.start_date.present?
      self.start_date
    else
      DateTime.now
    end
  end
  
  def end_date_rescued
    if self.end_date.present?
      self.end_date
    else
      DateTime.now
    end
    
  end
  
end

app/models/exp_category_post.rb
# -*- encoding : utf-8 -*-
class ExpCategoryPost < ActiveRecord::Base
end

app/models/exp_weblog_data.rb
# -*- encoding : utf-8 -*-
class ExpWeblogData < ActiveRecord::Base
end

app/models/exp_weblog_title.rb
# -*- encoding : utf-8 -*-
class ExpWeblogTitle < ActiveRecord::Base
end

app/models/information.rb
# -*- encoding : utf-8 -*-
class Information < ActiveRecord::Base
end

app/models/mailinglist.rb
# -*- encoding : utf-8 -*-
class Mailinglist < ActiveRecord::Base
  acts_as_xlsx

  set_primary_key :id
  validates :email, :presence => true, :uniqueness => true
end

app/models/mailingtemplate.rb
# -*- encoding : utf-8 -*-
class Mailingtemplate < ActiveRecord::Base
  validate :title, :description, :presence => true
  
  before_save :vol_increase
  
  def vol_increase
    self.vol = Mailingtemplate.all.size
  end
  
end

app/models/news.rb
# -*- encoding : utf-8 -*-
class News < ActiveRecord::Base
  has_attached_file :attachment 
end

app/models/pdf.rb
# -*- encoding : utf-8 -*-
class Pdf < ActiveRecord::Base
  has_attached_file :attachment, 
  :url => '/system/attachments/:id/:style/:filename',
  :path => 'public/system/attachments/:id/:style/:filename',
  :dependent => :destroy

  validates_attachment_content_type :attachment, :content_type => ["CDF V2 Document, No summary info", "application/unknown", "application/x-hwp", "application/haansofthwp", "application/vnd.hancom.hwp", "application/pdf", "application/octet-stream"]
  

  # do_not_validate_attachment_file_type :attachment

  belongs_to :pdfable, :polymorphic => true
end

app/models/picture.rb
# -*- encoding : utf-8 -*-
class Picture < ActiveRecord::Base
  has_attached_file :photo, :styles => {
    :main => "320x520", 
    :medium => '320x500#', 
    :thumb => '100x100#'
  }, 
  :url => '/system/photos/:id/:style/:filename',
  :path => 'public/system/photos/:id/:style/:filename',

  :dependent => :destroy 
   
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "application/octet-stream"]
  belongs_to :pictureable, :polymorphic => true
end

app/models/user.rb
# -*- encoding : utf-8 -*-

class User < ActiveRecord::Base

  
  def password
    @password
  end

  def password=(pwd)
    @password = pwd
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end


  def self.authenticate(login, password)
    user = self.find_by_login(login)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end
  
  private

  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt;
    Digest::SHA256.hexdigest(string_to_hash)
  end
  
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end  
  
end

app/helpers/educations_helper.rb
# -*- encoding : utf-8 -*-
module EducationsHelper
end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/helpers/news_helper.rb
# -*- encoding : utf-8 -*-
module NewsHelper
end

app/helpers/search_helper.rb
# -*- encoding : utf-8 -*-
module SearchHelper
end

app/helpers/searches_helper.rb
# -*- encoding : utf-8 -*-
module SearchesHelper
end

app/helpers/searchs_helper.rb
# -*- encoding : utf-8 -*-
module SearchsHelper
end

app/helpers/welcomes_helper.rb
# -*- encoding : utf-8 -*-
module WelcomesHelper
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>Designed and built by Wonyoung So</p>
</footer>

app/views/layouts/admin/_header.html.erb
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Total Museum of Contemporary Art', root_path, :class => 'brand' %>

        <ul class="nav">
            
          <% if params[:controller] == 'admin/currents' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'Main Page', admin_currents_path %></li>
          
          
          <% if params[:controller] == 'admin/news' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'News', admin_news_index_path %></li>
          
          <% if params[:controller] == 'admin/exhibitions' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'Exhibitions', admin_exhibitions_path %></li>
          
          <% if params[:controller] == 'admin/educations' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'Educations', admin_educations_path %></li>
          
          <% if params[:controller] == 'admin/events' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'Events', admin_events_path %></li>
          
          
          <% if params[:controller] == 'admin/mailinglists' || params[:controller] == 'admin/mailingtemplates' %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
          <%= link_to 'Mailing List', admin_mailinglists_path %></li>
          
        </ul>
      </div>
    </div>
  </div>
  